### ISSUE TITLE
How could i compile openfbx as windows static lib ?

### ISSUE THREAD

**Issue by flarive** [nem0/OpenFBX#101]
Hey !

Not an issue, a question 
Where could i find a x64 windows static lib of openfbx ? (openfbx.lib)

Or how could i compile repo source to produce openfbx.lib static lib ?

Thanks a lot !

I wanted to use the version on vcpkg website, but it was outdated so i have tried to upgrade openfbx vcpkg package to latest but not easy task.
https://vcpkg.io/en/packages?query=openfbx
https://github.com/microsoft/vcpkg/pull/42694

**Comment by nem0** [comment]
Hi, you can just add these 4 files https://github.com/nem0/OpenFBX/tree/master/src to your project.

**Comment by flarive** [comment]
Yes, thanks, i finally succeed !
It would be so great if you could update openfbx on vcpkg website.
I have tried to update it to latest but it's not easy.

Anyway, openfbx seems to be a very good lib :)
I'm going to use it my raytracer project.
https://github.com/flarive/Cortex-Raytracer

**Comment by nem0** [comment]
vcpkg was not created by me and I have no idea how it works. 
You might also be interested in https://github.com/ufbx/ufbx
