### ISSUE TITLE
Metadata creator

### ISSUE THREAD

**Issue by flarive** [nem0/OpenFBX#102]
How could i know if fbx export is coming from 3ds max or blender ?

Thanks a lot

**Comment by nem0** [comment]
You can try m_root_element ->
![image](https://github.com/user-attachments/assets/4ef5fbbb-ecc2-4935-8669-11c9cfcd1d49)

but there are no guarantees the value is there. I've never needed this so I'm not sure how reliable it is.

**Comment by flarive** [comment]
Ok, thanks a lot, i'm going to try !

**Comment by flarive** [comment]
Is there an easy way to find a key such as "Creator" or should i try to recursively loop to try to find a given key ?

**Comment by nem0** [comment]
There's nothing, even the internal functions are not recursive. You should be able to write such function based on findChild and resolve
