### ISSUE TITLE
Orthographic camera considered as perspective camera

### ISSUE THREAD

**Issue by flarive** [nem0/OpenFBX#105]
Hello,

I have set up an orthographic camera in 3ds max.

![max](https://github.com/user-attachments/assets/132109ac-3f3d-4501-ba6d-30de3a4b4568)

With your demo app, i can see the camera is orthographic (it's ok)

![debug](https://github.com/user-attachments/assets/02fc773d-1a8d-4c63-b2e0-0fbe5baf100b)

In my project using openfbx, the camera has an enum value of 0 (perspective)

auto enum_value = ofbxcam->getProjectionType();

May be the error is because the property is called "CameraProjectionType" in your demo, and in your code you seems to get "ProjectionType" property.
I think the default value (perspective) is always used because of this naming mismatch.

![code](https://github.com/user-attachments/assets/66233588-8ef5-4275-b087-be8943567eef)

**Comment by nem0** [comment]
See if the latest commit fixes this

**Comment by flarive** [comment]
Thanks ! I'm going to try :)
Could you also expose property CameraOrthoZoom please ?
I would love to be able to access it easily like that : ofbxcam->getOrthoZoom();

**Comment by flarive** [comment]
Yes, your fix works !

**Comment by flarive** [comment]
How could i get ortho zoom for my ortographic camera ?

**Comment by nem0** [comment]
I've added it.

**Comment by flarive** [comment]
Thank you so much !
