### ISSUE TITLE
Why don't you use the fbx sdk!

### ISSUE THREAD

**Issue by qwe5788319** [nem0/OpenFBX#17]
build project run studio.exe，fbx parsing error... .

use the www.sketchfab.com fbx resources  the success rate is very low。

**Comment by nem0** [comment]
I don't use fbx sdk because of its license. Do you have link to specific model that does not work?

**Comment by nem0** [comment]
I tried multiple files, only problems I could find were caused by #9

**Comment by qwe5788319** [comment]
[test.zip](https://github.com/nem0/OpenFBX/files/1273967/test.zip)  give you two fbx file testing

**Comment by qwe5788319** [comment]
I'm sorry to reply you so late

**Comment by nem0** [comment]
Thanks, I will look at it.

**Comment by nem0** [comment]
The first file loads fine for me, the second is in some very old version (6.1), which neither blender nor assimp can load. 

I will add support for these older versions.

**Comment by nem0** [comment]
It seems I won't add  support for these older versions :D
