### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by nem0** [nem0/OpenFBX#2]

**Comment by nem0** [comment]
Demo screenshot
![ofbx](https://user-images.githubusercontent.com/153526/27876079-eea3c872-61b5-11e7-9fce-3a7c558fb0d2.png)

**Comment by haikarainen** [comment]
![Please sir, may I have some more?](https://i.imgflip.com/1uty95.jpg)

## Questions / Assumptions

1. In `scene->getMesh(i)->getGeometry()->getMaterials()`, do this one also work like uv/normals, and each vertex has an index to the material it uses?
2. What the heck are clusters? They seem to be very connected to skeletons and vertex weights/indices.
3. How are skeletons and their animations laid out in your structures?  How do I get the bone hierarchy? How do I get the inverse bind pose etc.?

Cheers!

**Comment by haikarainen** [comment]
Just to answre myself a bit, and if anyone else wonders, this specific file shows some pretty detailed ofbx usage: https://github.com/nem0/LumixEngine/blob/master/src/renderer/editor/import_asset_dialog.cpp

**Comment by nem0** [comment]
* Yes
* OpenFBX mirrors fbx structure, so you can find more info about clusters here: http://docs.autodesk.com/FBX/2014/ENU/FBX-SDK-Documentation/cpp_ref/class_fbx_cluster.html
* Bone hierarchy and animations can be seen at the link you already found.

**Comment by haikarainen** [comment]
@nem0  Thanks buddy!  Yeah I realized this after reading up a little more about FBX. Hopefully this thread is of help to other people, however I've personally decided to write my own loader, as the format itself isn't too complicated.  This way I can fit the parsing of the loaded document to my own projects need :)

**Comment by nem0** [comment]
Good luck. It's not that hard to write a custom loader, especially when you can look at Assimp's and OpenFBX's source.
