### ISSUE TITLE
signed long long for time value

### ISSUE THREAD

**Issue by Neill3d** [nem0/OpenFBX#24]
Hi,

 thank you for your library! I'm using it to open fbx scene in my android application and I hope to add a support for some features from motionbuilder. 
 I've just figured out that in AnimationCurve you are storing values in unsigned long long, which will give unpredictable result when converting time to seconds as real value should be in signed long long, for managing negative time values as well (some animation could have stance pose in -100 frame for example)

**Comment by nem0** [comment]
Hi, do you have an example file I can test the issue with?

**Comment by Neill3d** [comment]
Hi, here is a scene with a pose in -25 frame. 
[testTimeValues.zip](https://github.com/nem0/OpenFBX/files/1896450/testTimeValues.zip)

**Comment by nem0** [comment]
Thanks, it should work now.
closed via fe71524af103731ee595f0c056e5cd4c4b5e9177
