### ISSUE TITLE
connection property-property is missing

### ISSUE THREAD

**Issue by Neill3d** [nem0/OpenFBX#26]
Hi,
 I've found that there is no support for property references (property-property connection type), that could be in a file when, for example, someone forgot to kill character control rig components.
 here is an example in ascii format

;NodeAttribute::, Model::Hips
C: "PP",738737744, "IK Reach Translation",842764320, "HipsEffector.IK Reach Translation"

and in code you are waiting for string, long, long
if (!isString(connection->first_property)
			|| !isLong(connection->first_property->next)
			|| !isLong(connection->first_property->next->next))
		{
			Error::s_message = "Invalid connection";
			return false;
		}

which don't suit well for PP connection type.
P.S. I've attached an example fbx.
[move1.zip](https://github.com/nem0/OpenFBX/files/1946995/move1.zip)

**Comment by nem0** [comment]
Thanks, I will look into it.
