### ISSUE TITLE
Just a thank you!

### ISSUE THREAD

**Issue by haikarainen** [nem0/OpenFBX#29]
For taking the time to publish your work on this. My game engine currently uses Assimp to import assets, but as you probably know, it's far from flawless, and a lot of meshes/rigs simply don't work. This seems like a much cleaner solution!

<3

**Comment by nem0** [comment]
Thanks. 
Assimp's internal fbx code is quite good, the issue is it has to transform FBX data to common Assimp format. Also it's much easier to fix an issue in OpenFBX than in Assimp with all its formats.
