### ISSUE TITLE
readProperty function question

### ISSUE THREAD

**Issue by marsp0** [nem0/OpenFBX#34]
Hey, thank you for making this lib :)

I was going through the code in the `readProperty` function and from what I understood (which can be completely wrong) the only values that we are getting from there are strings. Are there no other values that we can find there or am I missing something from the code ?

**Comment by nem0** [comment]
Hi,
[readProperty](https://github.com/nem0/OpenFBX/blob/master/src/ofbx.cpp#L511) returns ```OptionalError<Property*>``` and it can contain any value supported by fbx (floats, ints, strings, arrays). For example https://github.com/nem0/OpenFBX/blob/master/src/ofbx.cpp#L2029 get array of numbers from a property.

**Comment by marsp0** [comment]
Hey,

that makes sense. I have an additional question and if you would rather that I open a new issue (to keep topics separated) let me know.

I was searching around the FBX SDK to answer this question, but was not able to come to a useful conclusion. I am new to skeletal animation and am not able to properly connect the concepts that i have in my head to the classes that are in the library. If you can give me a hand here that would be greatly appreciate it.

Lets say I have the following :

1. Bones - describes a single bone in the skeleton
    - has offset matrix to move from root to bone space. Used in shader to move the model vertices to bone space
    - has localAnimationTransform
    - has globalAnimationTransform - used in shader to apply the animation and move the vertices to model space

2. Keyframe - contains the rotation/translation/scale at a certain time point
3. BoneAnimation - contains the array of keyframes for a single bone in a single animation.
4. Skeleton - contains the hierarchical information about the bones and updates the animation information at every frame.
5. Animation - contains a vector of bone animations
6. Animator - connects Skeleton and Animation and progresses the animation

If possible, can you tell me how the classes in the lib represent those concepts ?

**Comment by nem0** [comment]
you can see in https://github.com/nem0/LumixEngine/blob/32bc4d28c84ded0cd6ae2781d49518b29b44efeb/src/renderer/editor/fbx_importer.cpp#L906 what data is taken from ofbx to use in animation.

Bone can be any ofbx::object. ofbx::AnimationStack contains ofbx::AnimationLayer (usually just one) and each layer has ofbx::AnimationCurveNode for rotation/translation/scale
