### ISSUE TITLE
May be 2 bugs

### ISSUE THREAD

**Issue by cloudwu** [nem0/OpenFBX#36]
https://github.com/nem0/OpenFBX/blob/master/src/ofbx.cpp#L2926-L2937

It check whether the file is binary, calling `tokenizeText` when `tokenize` failed.  I think binary format version checking should be after trying `tokenizeText` .

https://github.com/nem0/OpenFBX/blob/master/src/ofbx.cpp#L602

`readElement` may returns `nullptr` , but not checking it when parsing children.

https://github.com/nem0/OpenFBX/blob/master/src/ofbx.cpp#L641-L649

`link = &(*link)->sibling;`  *link can be `nullptr` here.

**Comment by nem0** [comment]
Hi, tahnks for the report. You are right about the nullptr bug, however I do not understand why do you want ```tokenizeText``` before ```tokenize```.

**Comment by cloudwu** [comment]
If you parse an ASCII version of FBX as a binary version, it may trigger `if (version < 6200)` before calling `tokenizeText`. Because ASCII version of FBX doesn't have the header. 

Although ASCII text seldom use `\0`,  the `header->version` is always great than `0x01010101` in ASCII version, it's great than 6200, but I think check it after `tokenizeText` would be better.

**Comment by nem0** [comment]
Should be fixed
