### ISSUE TITLE
Number of vertex in FBX and OBJ are not equal

### ISSUE THREAD

**Issue by specy94** [nem0/OpenFBX#39]
Hi, thank you for this lib,

I tested the conversion of a simple shape (a cube, 8 vertices) with this algorithm and i found that the number of vertices written in .obj file was 36, with multiple vertex replications. What's wrong?

I expected that .obj files contains only 8 vertices.

**Comment by nem0** [comment]
Hi specy96, the library does not do any compression or indexing, that's up to the user.  In case of cube, there's 6 faces == 12 triangles == 36 vertices. Even though some vertices might be the same and therefore can be indexed, OpenFBX does no optimizations of any kind.
