### ISSUE TITLE
Unused var or bug?

### ISSUE THREAD

**Issue by asmaloney** [nem0/OpenFBX#40]
In **parseTemplates()**:

```cpp
if (subdef->id == "PropertyTemplate")
{
	DataView prop1 = def->first_property->value;
	DataView prop2 = subdef->first_property->value;
	std::string key((const char*)prop1.begin, prop1.end - prop1.begin);
	key += std::string((const char*)prop1.begin, prop1.end - prop1.begin);
	templates[key] = subdef;
}
```

Is `prop2` supposed to be used or is it extraneous?

**Comment by asmaloney** [comment]
Any thoughts on this one?

**Comment by nem0** [comment]
Sorry, I missed this. 
You are right, the line ```key += ...``` should use ```prop2```, but the function ```parseTemplates``` is never called. It's in potentially TODO state. I have not yet found an FBX file where this would cause problems.

**Comment by nem0** [comment]
https://github.com/nem0/OpenFBX/issues/4
