### ISSUE TITLE
Question about change

### ISSUE THREAD

**Issue by asmaloney** [nem0/OpenFBX#45]
There was a change in "[minor fixes](b934ba81ce129a5e491a59e672888bd05953a262)" that seems more than minor:

```cpp
	UpVector_AxisX = 0,
	UpVector_AxisY = 1,
	UpVector_AxisZ = 2
```
This actually fixes a problem I was having, but I'm wondering what the background is on the change?

(I remember looking at the official API and it was using `UpVector_AxisX = 1` which OpenFBX was before this change. It seemed to be giving me incorrect info.)

**Comment by nem0** [comment]
The author of the original code looked in fbx sdk docs and used those values. I only noticed this does not work when I started using it. There's no 3rd party information which indicates current code is correct other than it seems to work for all files I tried.

**Comment by asmaloney** [comment]
OK - thank you!
