### ISSUE TITLE
getRotationMatrix fall through in release build

### ISSUE THREAD

**Issue by asmaloney** [nem0/OpenFBX#46]
In *getRotationMatrix()*:

```cpp
switch (order)
{
	default:
	case RotationOrder::SPHERIC_XYZ: assert(false);
	case RotationOrder::EULER_XYZ: return rz * ry * rx;
```

In a release build, the assert statement is compiled away and `default` and `RotationOrder::SPHERIC_XYZ` both fall through to the `RotationOrder::EULER_XYZ` case.

If this is the intent, then I would suggest a comment because it isn't clear. If it's not, then `SPHERIC_XYZ` probably needs an error for the user and then `break;`.

(Also the style of putting `default` at the top is non-idiomatic and will throw readers off. In this case it isn't needed anyways since all the enum values are covered.)

**Comment by nem0** [comment]
There's no good way to solve this without exceptions, I changed it a bit (set error message) but I doubt anyone will really check that. Fortunately I've never seen a file with such rotation order.
