### ISSUE TITLE
Negative index?

### ISSUE THREAD

**Issue by isbdnt** [nem0/OpenFBX#48]
The fbx file is output of zbrush.
![image](https://user-images.githubusercontent.com/26591233/74399915-5dbcd880-4e57-11ea-9a29-c44ec91f8c68.png)

**Comment by nem0** [comment]
Does it crash or something? See https://github.com/nem0/OpenFBX/blob/master/src/ofbx.cpp#L2004

**Comment by isbdnt** [comment]
It didn't crash, there were no errors. Notice that the mesh is pretty large, about 6m triangles. Then I choose to use Autodesk FBX SDK, it just works well.

**Comment by nem0** [comment]
I'm a bit confused, what's the problem? Note: negative indices denotes the end of polygon (in this case triangles, since every third index is negative).
