### ISSUE TITLE
missing faces/indices

### ISSUE THREAD

**Issue by vichoconejeros** [nem0/OpenFBX#52]
Hi I'm trying to load the next model [messy tavern](https://sketchfab.com/3d-models/messy-tavern-40736fa5298c4e738633c51be872c4b1) (I have converted the obj file with blender). which looks good using the windows 3d Visor app
<img width="960" alt="2020-06-08" src="https://user-images.githubusercontent.com/10147674/83995541-aa0cb680-a927-11ea-9663-4f8670bb7249.png">

but after loading the file and creating the d3d12 stuff(my faces are in UINT16 so i had to drop the negative indexes) I see gaps in the faces of the model
<img width="960" alt="2020-06-08 (1)" src="https://user-images.githubusercontent.com/10147674/83995729-328b5700-a928-11ea-8765-97bbd612d2c8.png">
<img width="960" alt="2020-06-08 (2)" src="https://user-images.githubusercontent.com/10147674/83995742-3cad5580-a928-11ea-996e-ee3bbf173603.png">
<img width="960" alt="2020-06-08 (3)" src="https://user-images.githubusercontent.com/10147674/83995969-f278a400-a928-11ea-8043-4af435b51e69.png">

I'm not an expert in FBX parsing, but I think it's odd that some vertices are not referenced by the index buffer(ex: 2, 5, 8, etc..)

should I load those vertices myself in the index buffer? or it's a library issue?

Regards

**Comment by nem0** [comment]
The tavern looks ok in LumixEngine, try `ofbx::LoadFlags::TRIANGULATE` in `ofbx::load(...)`

**Comment by vichoconejeros** [comment]
changing to -idx -1 when idx%3==2 did the trick. thank you!
<img width="960" alt="2020-06-08 (4)" src="https://user-images.githubusercontent.com/10147674/84089894-349ff500-a9be-11ea-9d00-aacf69dbadac.png">
