### ISSUE TITLE
Alignment error when using an ARM processor

### ISSUE THREAD

**Issue by AlexAUT** [nem0/OpenFBX#58]
All DataView::toX functions directly cast the pointer without taking alignment into account. This unaligned access will only have a performance penalty on x86 CPUs, however, on ARM CPUs this results in a crash due to the unaligned memory access.
https://github.com/nem0/OpenFBX/blob/master/src/ofbx.cpp#L304

Copying into a stack variable is one way to remove the unaligned access, not sure if it is the most performant way to fix this.
```
double result;
memcpy(&result, begin, sizeof(double));
return result;
```

**Comment by nem0** [comment]
It's actually undefined behaviour the way it is now. I just did not care and did not expect it to be run on something else than PC HW. memcpy is the best solution, I will fix it soon, but I don't have ARM to test it.

**Comment by AlexAUT** [comment]
Thank you (and also for the great library). I could also create a quick pull-request if you want? Since I have already made the change in my local repo.

**Comment by nem0** [comment]
sure, PR  would be great, thanks.
