### ISSUE TITLE
How to get SystemUnit?

### ISSUE THREAD

**Issue by timi-liuliang** [nem0/OpenFBX#61]
I used this library in [Echo](https://github.com/timi-liuliang/echo) Engine, It's a very easy used library. Thank you very much.
but I want to know how can I get Scene's System Unit by this library?

Native Fbx sdk did it like this
```cpp
lScene->GetGlobalSettings().GetSystemUnit() == FbxSystemUnit::cm
```
in its documentation [Scene Axis and Unit Conversion](http://docs.autodesk.com/FBX/2014/ENU/FBX-SDK-Documentation/index.html?url=files/GUID-CC93340E-C4A1-49EE-B048-E898F856CFBF.htm,topicNumber=d30e8478)

But in Openfbx,  GlobalSettings don't have a variable about SystemUnit.
```cpp
struct GlobalSettings
{
	UpVector UpAxis = UpVector_AxisX;
	int UpAxisSign = 1;
	FrontVector FrontAxis = FrontVector_ParityOdd;
	int FrontAxisSign = 1;
	CoordSystem CoordAxis = CoordSystem_RightHanded;
	int CoordAxisSign = 1;
	int OriginalUpAxis = 0;
	int OriginalUpAxisSign = 1;
	float UnitScaleFactor = 1;
	float OriginalUnitScaleFactor = 1;
	double TimeSpanStart = 0L;
	double TimeSpanStop = 0L;
	FrameRate TimeMode = FrameRate_DEFAULT;
	float CustomFrameRate = -1.0f;
};

```

**Comment by nem0** [comment]
Hi, I suspect SystemUnit is just UnitScaleFactor. That's what I use to scale my meshes and everything works ok so far. If it does not work for you could you please provide an example fbx?

**Comment by timi-liuliang** [comment]
I'll try it. Thank you. great respect to you for your work.
