### ISSUE TITLE
Add samples on how to parse fbx files into 3D mesh

### ISSUE THREAD

**Issue by GCourtney27** [nem0/OpenFBX#63]
Adding a sample inside the project that shows how to parse the information obtained by OpenFBX would be useful instead of showing how to make an OBJ file from the FBX file in main.
By following the OBJ->FBX sample code inside main.cpp I am getting these results:
![image](https://user-images.githubusercontent.com/38294509/101129136-e6a72b00-35b5-11eb-9691-22811fdad7d7.png)
Obviously, it is an indexing problem (on my end) but I can't figure out how to index the data provided without a sample of some kind to follow.

**Comment by nem0** [comment]
Hi, you can see real world example here https://github.com/nem0/LumixEngine/blob/master/src/renderer/editor/fbx_importer.cpp#L847

**Comment by GCourtney27** [comment]
Thanks for that. It's an impressive example but pretty complicated to follow. I'd just like to import a simple static mesh with no skinning or culling structures applied.

**Comment by nem0** [comment]
I'm sorry, I don't have simpler example. For simple mesh, you just have to use vertices from `ofbx::Geometry::getVertices` and indices from `getFaceIndices`. Only catch is that if you don't use `ofbx::LoadFlags::TRIANGULATE`, negative indices signals end of polygon. That's how it's stored directly in FBX file and without triangulation ofbx just provides raw fbx data.
See https://github.com/nem0/OpenFBX/blob/master/demo/main.cpp#L280

**Comment by GCourtney27** [comment]
Oh okay, I tried writing the loop again and apparently in fbx if the index is negative that means it is the last index in the polygon (like you said) you need to make it positive then subtract one from it. In the sample code it was either make it positive or add one. So I replaced everything inside the indicies `for` loop with `idx = faceIndices[i]; if (idx < 0) idx = -(idx + 1);` then add the index to the list of indices and continue. That fixed the issue:
![image](https://user-images.githubusercontent.com/38294509/101228754-e492aa00-3651-11eb-81c6-03f1170267b6.png)
Thanks!
