### ISSUE TITLE
Crash in parseObjects if FBX has no geometry

### ISSUE THREAD

**Issue by Alexeyt89** [nem0/OpenFBX#64]
The importer crashes on importing animation fbx files, which have only skeleton and animations, but don't have mesh.

Here it tries to get the first value from parse_geom_jobs[0], but the array is empty.
`	
		(*job_processor)([](void* ptr){
			ParseGeometryJob* job = (ParseGeometryJob*)ptr;
			job->is_error = parseGeometry(*job->element, job->triangulate, job->geom).isError();
		}, job_user_ptr, &parse_geom_jobs[0], (u32)sizeof(parse_geom_jobs[0]), (u32)pars`

A solution would be to wrap this code into this check:
`if (!parse_geom_jobs.empty())
{
..
}`
Beside that Qt Creator and Visual Studio give tones of warnings about type conversions and other stuff.

**Comment by nem0** [comment]
Thanks, fixed in 4297358a33e8a8557d5413eb85f966db787c52c7
