### ISSUE TITLE
FrontAxis wrong ?

### ISSUE THREAD

**Issue by Renardjojo** [nem0/OpenFBX#68]
Hi !
I have a problem with the global settings of my FBX for the front axis. 
![bug](https://user-images.githubusercontent.com/55276408/131489408-75b1c740-4244-4662-9445-1e4ee22accc2.png)
As you can see, the front axis was parsed with the value of 2. But the enum only contains values for 0 and 1. 
![Capture d’écran 2021-08-31 125048](https://user-images.githubusercontent.com/55276408/131490416-af063336-f7f4-45b4-80da-3d99805919bd.png)
If I see the documentation for the FBX I saw that they enum start with 1. But it is the same for the Up axis and I don't have a problem with it. 
![Capture d’écran 2021-08-31 124929](https://user-images.githubusercontent.com/55276408/131489832-eed73eb2-5c40-45e9-ae19-9636a9d493e3.png)
Can you help me ?

**Comment by nem0** [comment]
Do you have an example fbx file? Accodring to fbx sdk docs, FrontAxis is indeed 1-2, not 0-1.

**Comment by Renardjojo** [comment]
According to fbx sdk docs, UpAxis is indeed 1-3, not 0-2 but I don't have problem with it. 
Sur I send you a link to my FBX

**Comment by nem0** [comment]
I tracked the change https://github.com/nem0/OpenFBX/commit/6b421d0c4d602723f41033b7b23627fd105f411e @mafiesto4 any ideas why?

**Comment by Renardjojo** [comment]
Do you also understand what even or odd front axis mean ? Even with the description of Autodesk I don't understand what it mean

**Comment by nem0** [comment]
from https://help.autodesk.com/view/FBX/2017/ENU/?guid=__cpp_ref_class_fbx_axis_system_html

> The EFrontVector specifies which axis has the front and back direction in the system. It is not an independent variable, which means it depends on EUpVector. The enum values ParityEven and ParityOdd denote the first one and the second one of the remain two axes in addition to the up axis.

> For example if the up axis is X, the remain two axes will be Y And Z, so the ParityEven is Y, and the ParityOdd is Z ; If the up axis is Y, the remain two axes will X And Z, so the ParityEven is X, and the ParityOdd is Z; If the up axis is Z, the remain two axes will X And Y, so the ParityEven is X, and the ParityOdd is Y.

I'm looking into Blender, it exports UpAxis in 0-2 range while enum from fbx sdk is in 1-3. FrontAxis in Blender is also different from fbx sdk. Question is if Blender is wrong or if fbx sdk transforms the data. I'm downloading 3dsmax to find out.

**Comment by Renardjojo** [comment]
Thx !
My model comes from to blender, which is possible.

**Comment by nem0** [comment]
3DSmax also exports UpAxis in 0-2, so I guess fbx sdk does some transformation there. However FrontAxis is 1-2. I think the safest thing to do is keep UpAxis in 0-2, since it works with both Blender and Autodesk. I will switch FrontVector from enum to int, so users can choose what to do.

**Comment by Renardjojo** [comment]
Enum is more readable and can be converted as int. Maybe let a comment is enought

**Comment by nem0** [comment]
Yes, enum is more readable, but unfortunately it depends on which software you export your files from. Safest bet is to ignore the FrontVector and use just UpVector.

**Comment by nem0** [comment]
0f77c1176fa139162f7e09fbd7e7da3a48e0ef2b

**Comment by mafiesto4** [comment]
Yeah this `FrontVector` is inconsistent. Good idea with changing it to int.

**Comment by Renardjojo** [comment]
The problem is that this data seems to me essential to understand our referential. For example with Z up and right-handed referential I have two solutions : 
![image](https://user-images.githubusercontent.com/55276408/131505477-3d1b94cf-3c9f-4a53-b7a3-f0274e56425d.png)
1 - Z up, X forward and Y left
2 - Z up, Y forward, X right

**Comment by nem0** [comment]
See `enum EPreDefinedAxisSystem` in https://help.autodesk.com/view/FBX/2017/ENU/?guid=__cpp_ref_class_fbx_axis_system_html, basically everything is `ParityOdd`. You can still use `FrontAxis` if you want, but it will change depending on the software you used to export your fbx file.

**Comment by alsed** [comment]
`UpAxis` is not the same as `UpVector`.
`FrontAxis` is not the same as `FrontVector` (which is actually a base parity).
And `CoordAxis` is definitely not the same as `CoordSystem`.

The problem lies in combining the raw data from the axes with the semantic interpretation of that data.

if `GlobalSettings` just copy the raw data, `UpVector`, `FrontVector` y `CoordSystem` can then be constructed:

```
// everything is an int
		get_property("UpAxis", UpAxis, int, toInt);
		get_property("UpAxisSign", UpAxisSign, int, toInt);
		get_property("FrontAxis", FrontAxis, int, toInt);
		get_property("FrontAxisSign", FrontAxisSign, int, toInt);
		get_property("CoordAxis", CoordAxis, int, toInt);
		get_property("CoordAxisSign", CoordAxisSign, int, toInt);

// the same change in the GlobalSettings constructor
```

Notice that then, the enum structures would not be necessary.

**Should ofbx derive UpVector, FrontVector or CoordSystem?**
If the anwer is yes, the ideal -i think- would be to create a new function, like `InterpretAxisSystem `, that takes the raw axis data and do it.

If so, the problem with `UpVector` being 0-2 or 1-3 should be easily solved:

```
int raw_up_axis = UpAxis;
int raw_front_axis = FrontAxis;
int raw_coord_axis = CoordAxis;

bool is_openfbx_convention =
    (raw_up_axis    >= 0 && raw_up_axis    <= 2) &&
    (raw_front_axis >= 0 && raw_front_axis <= 2) &&
    (raw_coord_axis >= 0 && raw_coord_axis <= 2);

if (!is_openfbx_convention) 
{
    raw_up_axis    -= 1;
    raw_front_axis -= 1;
    raw_coord_axis -= 1;
}
```

FrontVector and CoordSystem are more complex to derive, but the same idea applies.
