### ISSUE TITLE
Where can I found armature value ? (Question)

### ISSUE THREAD

**Issue by Renardjojo** [nem0/OpenFBX#69]
I try to find where is stored the armature value. Here is my fxb in ascii :
![image](https://user-images.githubusercontent.com/55276408/133119870-53d6c56e-1cae-444b-b2e3-900fd73fc32b.png)
I try to obtain this -90.0000093346673 value. 
I saw that the skin have the armature's name, so I have tested all its properties but nothing seems to be the right value.
![image](https://user-images.githubusercontent.com/55276408/133120118-947d4822-02bb-4e50-a2d8-cd5bbf6e07d0.png)
Can you help me to find it ?

Here my ascii FBX :
[HopeAnim1.zip](https://github.com/nem0/OpenFBX/files/7155859/HopeAnim1.zip)
Here my binary FBX:
[HopeAnim1.zip](https://github.com/nem0/OpenFBX/files/7155868/HopeAnim1.zip)

**Comment by nem0** [comment]
"Lcl Rotation" is returned by `getLocalRotation`. Are you sure you are calling it on correct object?
