### ISSUE TITLE
how to use blendshapes

### ISSUE THREAD

**Issue by dreakWang** [nem0/OpenFBX#74]
Hi, thanks for your project! A little question is that OpenFBX support blendshape, but the demo and the engine seems that haven't show hot to use blendshape. May you shed any light on how to use the blendshape in OpenFBX, thanks!

**Comment by nem0** [comment]
Hi, I have never used blendshapes. Blendshape support was done by @mafiesto4, maybe he can help.

**Comment by mafiesto4** [comment]
Hi, here is how you can access blend shapes data (per-mesh):
```cpp
const ofbx::Mesh* mesh = ..;
const ofbx::Geometry* geometry = mesh->getGeometry();
const ofbx::BlendShape* blendShape = geometry ->getBlendShape();
if (blendShape && blendShape->getBlendShapeChannelCount() > 0)
{
	for (int32 channelIndex = 0; channelIndex < blendShape->getBlendShapeChannelCount(); channelIndex++)
	{
		const ofbx::BlendShapeChannel* channel = blendShape->getBlendShapeChannel(channelIndex);

		// Use the last shape
		const int targetShapeCount = channel->getShapeCount();
		if (targetShapeCount == 0)
			continue;
		const ofbx::Shape* shape = channel->getShape(targetShapeCount - 1);
		if (shape->getVertexCount() != geometry->getVertexCount())
		{
			// Error: blend has different amount of vertices than mesh
			continue;
		}

		// Now you can use blend shape data:
		// name = shape->name
		// weight = channel->getShapeCount() > 1 ? (float)(channel->getDeformPercent() / 100.0) : 1.0f
		// vertices = shape->getVertices()
	}
}
```

Here is actual usage in Flax Engine: https://github.com/FlaxEngine/FlaxEngine/blob/master/Source/Engine/Tools/ModelTool/ModelTool.OpenFBX.cpp#L710
(tested on many various models)

Also, if you don't want to import blend shapes you can disable it on importer to improve import time with flag: `ofbx::LoadFlags::IGNORE_BLEND_SHAPE`.

**Comment by dreakWang** [comment]
thanks so much！
