### ISSUE TITLE
can't free the memory of the scene

### ISSUE THREAD

**Issue by mgerhardy** [nem0/OpenFBX#82]
```cpp
	ofbx::IScene *scene = ofbx::load(data, (int)size, (ofbx::u64)ofbx::LoadFlags::TRIANGULATE);
        [,...]
        delete scene;
```
`calling a protected destructor of class 'ofbx::IScene'`

**Comment by nem0** [comment]
Hi, just call [IScene::destroy](https://github.com/nem0/OpenFBX/blob/master/src/ofbx.h#L510) to delete the scene
