### ISSUE TITLE
Missing failure handling for `parseArrayRaw(...)` when parsing matrix in `parsePose(...)`?

### ISSUE THREAD

**Issue by TomTheFurry** [nem0/OpenFBX#88]
While in all other places calling `parseArrayRaw(...)` handle parsing failure by cascading the error, in this line [here](https://github.com/nem0/OpenFBX/blob/4013f0c14fe159fef2be990d1dcff3e3c7aad050/src/ofbx.cpp#L1858) the call is missing handling for parsing failure. It is unclear whether that is intended or not?

### Background info:
*This group of issues are discovered when our team is porting OpenFBX library to run natively on C#. Our company is planning to use OpenFBX to expend model loading support for our game (and game engine), as we are currently using block bench parsing and loading only which provides limited features. While the modified C# port is currently closed source and for internal use only, it is undecided whether we will release the port in any format once it is to a stage we are happy with.*

**Comment by nem0** [comment]
Thanks, it was not inteded. Fixed.
