### ISSUE TITLE
The library does not build under a C++11-compliant compiler.

### ISSUE THREAD

**Issue by LennyMcLennington** [nem0/OpenFBX#91]
In multiple parts of the library, aggregate initialization is used on structs with default member initializers. This is not valid in C++11, but is valid in C++14 and above. For this reason, the CMakeLists.txt should not specify C++11 as the required standard, as the actual required standard is C++14.

Currently I need to manually patch the CMakeLists before I can use the library.

Reference: https://en.cppreference.com/w/cpp/language/aggregate_initialization

**Comment by nem0** [comment]
Hi, I'm closing this since cmake is not supported by me. It's been provided by community (@fran6co). I'm open to PRs.
