### ISSUE TITLE
Adding OpenFBX to conda-forge for Pixi packaging

### ISSUE THREAD

**Issue by jeongseok-meta** [nem0/OpenFBX#97]
Hello @nem0, I am considering adding OpenFBX to [conda-forge](https://github.com/conda-forge/staged-recipes) so that it can be used in a cross-platform package manager called [Pixi](https://prefix.dev/). Would you be interested in adding tags to OpenFBX for this packaging? Thank you!

**Comment by nem0** [comment]
Hi, do you mean github tags in the right column? If so, sure, why not. Let me know when and I will add it.

**Comment by jeongseok-meta** [comment]
Great! Yes, adding [git tags](https://git-scm.com/book/en/v2/Git-Basics-Tagging) is necessary for versioning in package managers. We can start with version 0.1.0 or 0.0.1, depending on your preference.

It is generally recommended to follow [semantic versioning](https://semver.org/). If the project is still under heavy development with frequent API changes, we could keep the major version at zero and then move to version 1.0.0 once it reaches stability.

**Comment by nem0** [comment]
https://github.com/nem0/OpenFBX/releases/tag/v0.9

**Comment by jeongseok-meta** [comment]
Awesome, thank you!
